### ISSUE TITLE
 emojis not loaded

### ISSUE THREAD

**Issue by Chris55** [4ch1m/github-markdown-emojis#3]
hi

Installed this plugin, but it fails to load the emojis unfortunately. 

![image](https://github.com/4ch1m/github-markdown-emojis/assets/8018327/043e006f-b8c4-4da0-86c5-2f3264a67352)

My config:

WebStorm 2023.2
Build #WS-232.8660.143, built on July 21, 2023
Licensed to xxxxxxxxxx
Subscription is active until xxxx.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4060M
Cores: 16
Non-Bundled Plugins:
    CMD Support (1.0.5)
    org.jetbrains.erlang (0.11.1205)
    com.intellij.ideolog (222.1.0.0)
    org.sonarlint.idea (8.4.0.73538)
    com.intellij.properties (232.8660.88)
    de.achimonline.github_markdown_emojis (1.3.0)
    com.intellij.database (232.8660.129)

**Comment by 4ch1m** [comment]
The images/icons are fetched from the internet.

Does your workstation/IDE have access to web?

e.g.

```
https://github.githubassets.com/images/icons/emoji/unicode/1f604.png?v8
```

**Comment by Chris55** [comment]
yes access to the web (but using corporate proxy)

web access works fine because was able to install the plug-in from the Webstorm plugging manager, and Webstorm upgrade is working fine too

**Comment by 4ch1m** [comment]
Okay.

The screenshot you provided basically shows the integrated "webpage" which pulls the images from the internet.
Maybe your proxy is blocking access to these resources?!

Do you get the image if you put the example-url from above into a webbrowser on your workstation?

**Comment by Chris55** [comment]
Yes I'm able to access the resource

![image](https://github.com/4ch1m/github-markdown-emojis/assets/8018327/54705028-53df-415f-a44d-8e402a3d1b45)

**Comment by 4ch1m** [comment]
I'm sorry. I have no other idea/clue why images are not loading on your end.
