### ISSUE TITLE
Bug: Unable to request JSON data for 'GitHub Markdown Emojis'.

### ISSUE THREAD

**Issue by chrishough** [4ch1m/github-markdown-emojis#5]
I just started getting the error `Unable to request JSON data for 'GitHub Markdown Emojis'.`

Any ideas on how to debug this? Happy to help

**Comment by 4ch1m** [comment]
Hi there,

not a bug... works fine for me.

Maybe an issue with your internet connection?!

Check if `https://api.github.com/emojis` is callable from your machine and returns valid results.

This can also be configured in the plugin's settings (in case you're behind a firewall and want to host it yourself):

![image](https://github.com/4ch1m/github-markdown-emojis/assets/3408832/949a49f3-f4cf-4a32-a214-d1e514cbbbf5)

**Comment by chrishough** [comment]
Not behind a firewall, and when I click on the url it works. This was already set, thoughts?
<img width="439" alt="Screenshot 2024-01-26 at 8 44 36 AM" src="https://github.com/4ch1m/github-markdown-emojis/assets/744056/17eef23b-efba-4e54-8a33-56566e27150c">

**Comment by 4ch1m** [comment]
> Not behind a firewall, and when I click on the url it works.

The API-URL to GitHub is not "clickable".
This is the settings-dialog; the API-URL can be changed there (if needed).

> This was already set,

Yes. Of course. It's the valid URL to GitHub's API.

> thoughts?

Nope. Sorry.
Unfortunately I can't help you with this.
